// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: httpgate.proto

/*
Package iproto is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package iproto

import (
	"context"
	"errors"
	"io"
	"net/http"
	"time"

	"github.com/golang/protobuf/proto"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
	grpcpool "github.com/processout/grpc-go-pool"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray

func request_RestfulGateway_Backendsvr1_Method1_0(ctx context.Context, marshaler runtime.Marshaler, client Backendsvr1Client, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Method1Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.Method1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func request_RestfulGateway_Backendsvr2_Method2_0(ctx context.Context, marshaler runtime.Marshaler, client Backendsvr2Client, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq Method2Request
	var metadata runtime.ServerMetadata

	newReader, berr := utilities.IOReaderFactory(req.Body)
	if berr != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", berr)
	}
	if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.Method2(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

// type HttpPrehandler func(string, *http.Request) (int, bool)
// type HttpDoneHandler func(string, proto.Message, http.ResponseWriter, *http.Request)
// type QpsHandler func(time.Duration)

// RegisterRestfulGatewayHandlerClient registers the http handlers for service RestfulGateway
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "RestfulGatewayClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "RestfulGatewayClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "{@target}Client" to call the correct interceptors.
// @param getEndpoint: a callback func( 'package.Service/Method' ) 'endpoint address'
// @param endCallback: a callback when grpc end, then callback('package.Service/Method' string, reply proto.Message) bool[false:quit]
// @param getClientConn: a callback func( 'package.Service/Method' )(conn, error) to get long connection by method
func RegisterRestfulGatewayHandlerClient(
	ctx context.Context,
	mux *runtime.ServeMux,
	opts []grpc.DialOption,
	getEndpoint func(string) string,
	getClientConn func(string) (*grpcpool.ClientConn, error),
	beginHandler func(string, *http.Request) (int, bool),
	doneHandler func(string, proto.Message, http.ResponseWriter, *http.Request),
	qpsHandler func(time.Duration)) error {

	makeConn := func(meth string) (*grpc.ClientConn, error, func()) {
		if getClientConn != nil {
			conn, err := getClientConn(meth)
			if err != nil {
				return nil, err, func() {}
			}
			return conn.ClientConn, nil, func() { conn.Close() }
		}
		addr := getEndpoint(meth)
		conn, err := grpc.Dial(addr, opts...)
		return conn, err, func() { conn.Close() }
	}

	// 注册Backendsvr1/Method1传输方法入口
	// 后端服务1
	// 注释
	mux.Handle("POST", pattern_RestfulGateway_Backendsvr1_Method1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		begin := time.Now()
		defer qpsHandler(time.Since(begin))
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)

		meth := "iproto.Backendsvr1/Method1"
		if code, ok := beginHandler(meth, req); code == http.StatusAccepted {
			if !ok {
				runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, errors.New("not login yet"))
				return
			}
		} else {
			runtime.OtherErrorHandler(w, req, http.StatusText(code), code)
			return
		}

		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		conn, err, closeFunc := makeConn(meth)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		closeFunc()

		client := NewBackendsvr1Client(conn)

		resp, md, err := request_RestfulGateway_Backendsvr1_Method1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		doneHandler(meth, resp, w, req)

		forward_RestfulGateway_Backendsvr1_Method1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	// 注册Backendsvr2/Method2传输方法入口
	// 后端服务2
	// 注释
	mux.Handle("POST", pattern_RestfulGateway_Backendsvr2_Method2_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		begin := time.Now()
		defer qpsHandler(time.Since(begin))
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)

		meth := "iproto.Backendsvr2/Method2"
		if code, ok := beginHandler(meth, req); code == http.StatusAccepted {
			if !ok {
				runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, errors.New("not login yet"))
				return
			}
		} else {
			runtime.OtherErrorHandler(w, req, http.StatusText(code), code)
			return
		}

		rctx, err := runtime.AnnotateContext(ctx, mux, req)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		conn, err, closeFunc := makeConn(meth)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		closeFunc()

		client := NewBackendsvr2Client(conn)

		resp, md, err := request_RestfulGateway_Backendsvr2_Method2_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		doneHandler(meth, resp, w, req)

		forward_RestfulGateway_Backendsvr2_Method2_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_RestfulGateway_Backendsvr1_Method1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "gw", "method1"}, "", runtime.AssumeColonVerbOpt(true)))

	pattern_RestfulGateway_Backendsvr2_Method2_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2}, []string{"v1", "gw", "method2"}, "", runtime.AssumeColonVerbOpt(true)))
)

var (
	forward_RestfulGateway_Backendsvr1_Method1_0 = runtime.ForwardResponseMessage

	forward_RestfulGateway_Backendsvr2_Method2_0 = runtime.ForwardResponseMessage
)
